#pragma once
#include <Godot.hpp>
#include <SceneTree.hpp>
#include <AnimatedSprite.hpp>
#include <AnimationPlayer.hpp>
#include <Dictionary.hpp>
#include <Area2D.hpp>
#include <iostream>
#include <ResourceLoader.hpp>
#include <PackedScene.hpp>
#include <Node2D.hpp>
#include <AnimationTree.hpp>
#include <AnimationNodeStateMachinePlayback.hpp>
#include <KinematicBody2D.hpp>
#include <Input.hpp>
#include <InputEvent.hpp>
#include <GlobalConstants.hpp>
#include <Reference.hpp>
#include <Timer.hpp>
#include <Control.hpp>
#include <TextureRect.hpp>
#include <cstdlib>
#include <AudioStreamPlayer.hpp>
#include <AudioServer.hpp>
#include <AudioStream.hpp>
#include <CollisionShape2D.hpp>